env: local

paths:
  model_path: "../outputs/pretraining/test/finetune_TEST_OUTCOME_censored_24_hours_pre_TEST_CENSOR_followup_start_at_index_date_test"
  # data_dir: "../outputs/pretraining/test/finetune_TEST_OUTCOME_censored_24_hours_pre_year2015_month1_day1_followup_start_at_index_date_test" 
  run_name: "shap_fi"

data:
  min_len: 1
  # preprocess: True
shap:
  n_background_samples: 10

dataloader:
  batch_size: 16
  
